services:
  service:
    restart: unless-stopped
    build: .
    entrypoint: sh run_service.sh
    ports:
      - "8000:8000"

  postgres:
    restart: unless-stopped
    image: "postgres:15"
    hostname: ${DATABASE_HOST}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 5s
      retries: 10
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data
