# Generated by Django 5.2b1 on 2025-03-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='tag',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
